### ISSUE TITLE
Insert required_if validation for 690/691$n

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#394]
something like 
```yaml
"690": 
  tags:
    a:
      required_if:
        "690": "n"
```
